export { default as AddUser } from "./AddUser"
export { default as CalculateWealth } from "./CalculateWealth"
export { default as DoubleMoney } from "./DoubleMoney"
export { default as ShowOnlyMillionaires } from "./ShowOnlyMillionaires"
export { default as SortByRichest } from "./SortByRichest"
